name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to build release from (defaults to tip of main)"

jobs:
  build-ui:
    name: Build UI Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install UI dependencies
        run: pnpm --filter ./ui install

      - name: Build UI asset
        run: pnpm --filter ./ui build

      - name: Draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          draft: false
          make_latest: false
          body_path: CHANGELOG.md
          files: |
            ui/dist/extension.tar
